# This file is automatically generated, you probably don't want to edit this

ralidOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ralidOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            hasRetest = FALSE,
            varsRetest = NULL,
            eqLower = -0.1,
            eqUpper = 0.1,
            confLevel = 0.95,
            nBoot = 1000,
            clinicalLower = 0,
            clinicalUpper = 0,
            showBA = TRUE,
            overlayEquivRegion = FALSE,
            showMountain = TRUE,
            doTOST = TRUE,
            showTOSTDecisionCurve = FALSE,
            showICC = TRUE,
            showErrorMetrics = TRUE,
            doWithinSession = FALSE,
            wsMeasure1 = NULL,
            wsMeasure2 = NULL,
            wsMeasure3 = NULL,
            wsMeasure4 = NULL,
            wsMeasure5 = NULL, ...) {

            super$initialize(
                package="ralid",
                name="ralid",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..hasRetest <- jmvcore::OptionBool$new(
                "hasRetest",
                hasRetest,
                default=FALSE)
            private$..varsRetest <- jmvcore::OptionVariables$new(
                "varsRetest",
                varsRetest,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..eqLower <- jmvcore::OptionNumber$new(
                "eqLower",
                eqLower,
                default=-0.1)
            private$..eqUpper <- jmvcore::OptionNumber$new(
                "eqUpper",
                eqUpper,
                default=0.1)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=0.95,
                min=0.5,
                max=0.999)
            private$..nBoot <- jmvcore::OptionInteger$new(
                "nBoot",
                nBoot,
                default=1000,
                min=100,
                max=10000)
            private$..clinicalLower <- jmvcore::OptionNumber$new(
                "clinicalLower",
                clinicalLower,
                default=0)
            private$..clinicalUpper <- jmvcore::OptionNumber$new(
                "clinicalUpper",
                clinicalUpper,
                default=0)
            private$..showBA <- jmvcore::OptionBool$new(
                "showBA",
                showBA,
                default=TRUE)
            private$..overlayEquivRegion <- jmvcore::OptionBool$new(
                "overlayEquivRegion",
                overlayEquivRegion,
                default=FALSE)
            private$..showMountain <- jmvcore::OptionBool$new(
                "showMountain",
                showMountain,
                default=TRUE)
            private$..doTOST <- jmvcore::OptionBool$new(
                "doTOST",
                doTOST,
                default=TRUE)
            private$..showTOSTDecisionCurve <- jmvcore::OptionBool$new(
                "showTOSTDecisionCurve",
                showTOSTDecisionCurve,
                default=FALSE)
            private$..showICC <- jmvcore::OptionBool$new(
                "showICC",
                showICC,
                default=TRUE)
            private$..showErrorMetrics <- jmvcore::OptionBool$new(
                "showErrorMetrics",
                showErrorMetrics,
                default=TRUE)
            private$..doWithinSession <- jmvcore::OptionBool$new(
                "doWithinSession",
                doWithinSession,
                default=FALSE)
            private$..wsMeasure1 <- jmvcore::OptionVariables$new(
                "wsMeasure1",
                wsMeasure1,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..wsMeasure2 <- jmvcore::OptionVariables$new(
                "wsMeasure2",
                wsMeasure2,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..wsMeasure3 <- jmvcore::OptionVariables$new(
                "wsMeasure3",
                wsMeasure3,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..wsMeasure4 <- jmvcore::OptionVariables$new(
                "wsMeasure4",
                wsMeasure4,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..wsMeasure5 <- jmvcore::OptionVariables$new(
                "wsMeasure5",
                wsMeasure5,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))

            self$.addOption(private$..vars)
            self$.addOption(private$..hasRetest)
            self$.addOption(private$..varsRetest)
            self$.addOption(private$..eqLower)
            self$.addOption(private$..eqUpper)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..nBoot)
            self$.addOption(private$..clinicalLower)
            self$.addOption(private$..clinicalUpper)
            self$.addOption(private$..showBA)
            self$.addOption(private$..overlayEquivRegion)
            self$.addOption(private$..showMountain)
            self$.addOption(private$..doTOST)
            self$.addOption(private$..showTOSTDecisionCurve)
            self$.addOption(private$..showICC)
            self$.addOption(private$..showErrorMetrics)
            self$.addOption(private$..doWithinSession)
            self$.addOption(private$..wsMeasure1)
            self$.addOption(private$..wsMeasure2)
            self$.addOption(private$..wsMeasure3)
            self$.addOption(private$..wsMeasure4)
            self$.addOption(private$..wsMeasure5)
        }),
    active = list(
        vars = function() private$..vars$value,
        hasRetest = function() private$..hasRetest$value,
        varsRetest = function() private$..varsRetest$value,
        eqLower = function() private$..eqLower$value,
        eqUpper = function() private$..eqUpper$value,
        confLevel = function() private$..confLevel$value,
        nBoot = function() private$..nBoot$value,
        clinicalLower = function() private$..clinicalLower$value,
        clinicalUpper = function() private$..clinicalUpper$value,
        showBA = function() private$..showBA$value,
        overlayEquivRegion = function() private$..overlayEquivRegion$value,
        showMountain = function() private$..showMountain$value,
        doTOST = function() private$..doTOST$value,
        showTOSTDecisionCurve = function() private$..showTOSTDecisionCurve$value,
        showICC = function() private$..showICC$value,
        showErrorMetrics = function() private$..showErrorMetrics$value,
        doWithinSession = function() private$..doWithinSession$value,
        wsMeasure1 = function() private$..wsMeasure1$value,
        wsMeasure2 = function() private$..wsMeasure2$value,
        wsMeasure3 = function() private$..wsMeasure3$value,
        wsMeasure4 = function() private$..wsMeasure4$value,
        wsMeasure5 = function() private$..wsMeasure5$value),
    private = list(
        ..vars = NA,
        ..hasRetest = NA,
        ..varsRetest = NA,
        ..eqLower = NA,
        ..eqUpper = NA,
        ..confLevel = NA,
        ..nBoot = NA,
        ..clinicalLower = NA,
        ..clinicalUpper = NA,
        ..showBA = NA,
        ..overlayEquivRegion = NA,
        ..showMountain = NA,
        ..doTOST = NA,
        ..showTOSTDecisionCurve = NA,
        ..showICC = NA,
        ..showErrorMetrics = NA,
        ..doWithinSession = NA,
        ..wsMeasure1 = NA,
        ..wsMeasure2 = NA,
        ..wsMeasure3 = NA,
        ..wsMeasure4 = NA,
        ..wsMeasure5 = NA)
)

ralidResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ralidResults",
    inherit = jmvcore::Group,
    active = list(
        cccTable = function() private$.items[["cccTable"]],
        baStats = function() private$.items[["baStats"]],
        baSummary = function() private$.items[["baSummary"]],
        errorMetrics = function() private$.items[["errorMetrics"]],
        tost = function() private$.items[["tost"]],
        iccTable = function() private$.items[["iccTable"]],
        iccRetest = function() private$.items[["iccRetest"]],
        withinSession = function() private$.items[["withinSession"]],
        baPlot = function() private$.items[["baPlot"]],
        mountainPlot = function() private$.items[["mountainPlot"]],
        tostEquivPlot = function() private$.items[["tostEquivPlot"]],
        tostDecisionPlot = function() private$.items[["tostDecisionPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Agreement, Equivalence & Reliability")
            self$add(jmvcore::Table$new(
                options=options,
                name="cccTable",
                title="Concordance correlation",
                rows=0,
                columns=list(
                    list(
                        `name`="pair", 
                        `title`="Pair", 
                        `type`="text"),
                    list(
                        `name`="ccc", 
                        `title`="CCC", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="lower", 
                        `title`="Lower CI", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper CI", 
                        `type`="number"),
                    list(
                        `name`="r", 
                        `title`="Pearson r", 
                        `type`="number"),
                    list(
                        `name`="cb", 
                        `title`="Bias correction", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="baStats",
                title="Bland-Altman statistics (for first pair)",
                rows=1,
                columns=list(
                    list(
                        `name`="bias", 
                        `title`="Mean difference", 
                        `type`="number"),
                    list(
                        `name`="sdDiff", 
                        `title`="SD of differences", 
                        `type`="number"),
                    list(
                        `name`="loaLower", 
                        `title`="Lower LoA", 
                        `type`="number"),
                    list(
                        `name`="loaUpper", 
                        `title`="Upper LoA", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="baSummary",
                title="Clinical interpretation of LoA"))
            self$add(jmvcore::Table$new(
                options=options,
                name="errorMetrics",
                title="Error metrics (for first pair)",
                rows=9,
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tost",
                title="TOST equivalence test (for first pair)",
                rows=1,
                columns=list(
                    list(
                        `name`="meanDiff", 
                        `title`="Mean difference", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower bound", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper bound", 
                        `type`="number"),
                    list(
                        `name`="tLower", 
                        `title`="t (lower)", 
                        `type`="number"),
                    list(
                        `name`="pLower", 
                        `title`="p (lower)", 
                        `type`="number"),
                    list(
                        `name`="tUpper", 
                        `title`="t (upper)", 
                        `type`="number"),
                    list(
                        `name`="pUpper", 
                        `title`="p (upper)", 
                        `type`="number"),
                    list(
                        `name`="pTOST", 
                        `title`="max p (TOST)", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="iccTable",
                title="Intraclass correlations (all measures as raters at Time 1)",
                rows=6,
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="type", 
                        `title`="Type", 
                        `type`="text"),
                    list(
                        `name`="unit", 
                        `title`="Unit", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="ICC", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="iccRetest",
                title="Test-retest reliability",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="icc", 
                        `title`="ICC (consistency)", 
                        `type`="number"),
                    list(
                        `name`="sem", 
                        `title`="SEM (test-retest)", 
                        `type`="number"),
                    list(
                        `name`="mdc95", 
                        `title`="MDC95 (test-retest)", 
                        `type`="number"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="withinSession",
                title="Within-session repeatability (up to 5 measures)",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="nTrials", 
                        `title`="Trials", 
                        `type`="integer"),
                    list(
                        `name`="iccSingle", 
                        `title`="ICC (single)", 
                        `type`="number"),
                    list(
                        `name`="iccAverage", 
                        `title`="ICC (average)", 
                        `type`="number"),
                    list(
                        `name`="sem", 
                        `title`="SEM (within-session)", 
                        `type`="number"),
                    list(
                        `name`="cv", 
                        `title`="CV (%)", 
                        `type`="number"),
                    list(
                        `name`="mdc95", 
                        `title`="MDC95 (within-session)", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="baPlot",
                title="Bland-Altman plot (for first pair)",
                renderFun=".baPlot",
                width=480,
                height=360))
            self$add(jmvcore::Image$new(
                options=options,
                name="mountainPlot",
                title="Mountain plot (for first pair)",
                renderFun=".mountainPlot",
                width=480,
                height=360))
            self$add(jmvcore::Image$new(
                options=options,
                name="tostEquivPlot",
                title="Equivalence region plot (TOST, first pair)",
                renderFun=".tostEquivPlot",
                width=480,
                height=300))
            self$add(jmvcore::Image$new(
                options=options,
                name="tostDecisionPlot",
                title="TOST decision curve (first pair)",
                renderFun=".tostDecisionPlot",
                width=480,
                height=300))}))

ralidBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ralidBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ralid",
                name = "ralid",
                version = c(0,1,0),
                options = options,
                results = ralidResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Agreement, Equivalence & Reliability
#'
#' 
#' @param data .
#' @param vars .
#' @param hasRetest .
#' @param varsRetest .
#' @param eqLower .
#' @param eqUpper .
#' @param confLevel .
#' @param nBoot .
#' @param clinicalLower .
#' @param clinicalUpper .
#' @param showBA .
#' @param overlayEquivRegion .
#' @param showMountain .
#' @param doTOST .
#' @param showTOSTDecisionCurve .
#' @param showICC .
#' @param showErrorMetrics .
#' @param doWithinSession .
#' @param wsMeasure1 .
#' @param wsMeasure2 .
#' @param wsMeasure3 .
#' @param wsMeasure4 .
#' @param wsMeasure5 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$cccTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$baStats} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$baSummary} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$errorMetrics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tost} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$iccTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$iccRetest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$withinSession} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$baPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mountainPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$tostEquivPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$tostDecisionPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$cccTable$asDF}
#'
#' \code{as.data.frame(results$cccTable)}
#'
#' @export
ralid <- function(
    data,
    vars,
    hasRetest = FALSE,
    varsRetest,
    eqLower = -0.1,
    eqUpper = 0.1,
    confLevel = 0.95,
    nBoot = 1000,
    clinicalLower = 0,
    clinicalUpper = 0,
    showBA = TRUE,
    overlayEquivRegion = FALSE,
    showMountain = TRUE,
    doTOST = TRUE,
    showTOSTDecisionCurve = FALSE,
    showICC = TRUE,
    showErrorMetrics = TRUE,
    doWithinSession = FALSE,
    wsMeasure1,
    wsMeasure2,
    wsMeasure3,
    wsMeasure4,
    wsMeasure5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ralid requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(varsRetest)) varsRetest <- jmvcore::resolveQuo(jmvcore::enquo(varsRetest))
    if ( ! missing(wsMeasure1)) wsMeasure1 <- jmvcore::resolveQuo(jmvcore::enquo(wsMeasure1))
    if ( ! missing(wsMeasure2)) wsMeasure2 <- jmvcore::resolveQuo(jmvcore::enquo(wsMeasure2))
    if ( ! missing(wsMeasure3)) wsMeasure3 <- jmvcore::resolveQuo(jmvcore::enquo(wsMeasure3))
    if ( ! missing(wsMeasure4)) wsMeasure4 <- jmvcore::resolveQuo(jmvcore::enquo(wsMeasure4))
    if ( ! missing(wsMeasure5)) wsMeasure5 <- jmvcore::resolveQuo(jmvcore::enquo(wsMeasure5))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(varsRetest), varsRetest, NULL),
            `if`( ! missing(wsMeasure1), wsMeasure1, NULL),
            `if`( ! missing(wsMeasure2), wsMeasure2, NULL),
            `if`( ! missing(wsMeasure3), wsMeasure3, NULL),
            `if`( ! missing(wsMeasure4), wsMeasure4, NULL),
            `if`( ! missing(wsMeasure5), wsMeasure5, NULL))


    options <- ralidOptions$new(
        vars = vars,
        hasRetest = hasRetest,
        varsRetest = varsRetest,
        eqLower = eqLower,
        eqUpper = eqUpper,
        confLevel = confLevel,
        nBoot = nBoot,
        clinicalLower = clinicalLower,
        clinicalUpper = clinicalUpper,
        showBA = showBA,
        overlayEquivRegion = overlayEquivRegion,
        showMountain = showMountain,
        doTOST = doTOST,
        showTOSTDecisionCurve = showTOSTDecisionCurve,
        showICC = showICC,
        showErrorMetrics = showErrorMetrics,
        doWithinSession = doWithinSession,
        wsMeasure1 = wsMeasure1,
        wsMeasure2 = wsMeasure2,
        wsMeasure3 = wsMeasure3,
        wsMeasure4 = wsMeasure4,
        wsMeasure5 = wsMeasure5)

    analysis <- ralidClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

